# Generated by Django 5.2.10 on 2026-01-29 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("group_size", models.PositiveIntegerField(blank=True, null=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("HOTSPOT", "Hotspot"),
                            ("SIGHT", "Sight"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("CONTACTED", "Contacted"),
                            ("CLOSED", "Closed"),
                            ("SPAM", "Spam"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "reference_token",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
            ],
        ),
    ]
