# Generated by Django 5.2.10 on 2026-01-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotspot",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True, help_text="Typical duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of tag strings e.g. ['tea', 'nature']",
            ),
        ),
    ]
