# Generated by Django 5.2.10 on 2026-01-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_hotspot_accessibility_notes_hotspot_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotspot",
            name="approx_travel_time_min",
            field=models.IntegerField(
                blank=True, help_text="Approx travel time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="distance_band",
            field=models.CharField(
                choices=[("NEAR", "Near"), ("MEDIUM", "Medium"), ("FAR", "Far")],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="nearest_transport_hub_name",
            field=models.CharField(
                blank=True, help_text="Name of nearest hub", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="nearest_transport_hub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUS_STAND", "Bus Stand"),
                    ("RAILWAY_STATION", "Railway Station"),
                    ("TAXI_POINT", "Taxi Point"),
                    ("FERRY", "Ferry"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
