# Generated by Django 5.2.10 on 2026-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0004_hotspot_approx_travel_time_min_hotspot_distance_band_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hotspot",
            name="hotspot_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard Hotspot"), ("SIGHT", "Sight")],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="sights_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONASTERY", "Monastery"),
                    ("VIEWPOINT", "Viewpoint"),
                    ("HERITAGE", "Heritage"),
                    ("NATURE", "Nature"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
