# Generated by Django 5.2.10 on 2026-01-28 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrowdAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("district_id", models.CharField(max_length=50)),
                ("hotspot_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CCTV_EDGE", "CCTV Edge"),
                            ("MANUAL", "Manual"),
                            ("OTHER", "Other"),
                        ],
                        default="CCTV_EDGE",
                        max_length=50,
                    ),
                ),
                (
                    "density_state",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=50,
                    ),
                ),
                ("count_15min", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("district_id", models.CharField(blank=True, max_length=50, null=True)),
                ("label", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=50)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DistrictRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("district_id", models.CharField(max_length=50)),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("WETLAND", "Wetland"),
                            ("FOREST", "Forest"),
                            ("BORDER", "Border"),
                            ("WEATHER", "Weather"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=50,
                    ),
                ),
                ("start_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
