# Generated by Django 5.2.10 on 2026-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_connectcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="identity_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="identity_value",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("INDIAN", "Indian National"),
                    ("FOREIGN", "Foreign National"),
                ],
                default="INDIAN",
                max_length=20,
            ),
        ),
    ]
