from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid
from shared.contracts.enums import UserRole, KYCStatus

class User(AbstractUser):
    # Alias for backward compatibility and model field usage
    Role = UserRole
    # KYCStatus is already imported with the same name, but we can assign it to class attribute if needed
    # defaulting to referencing the imported class for the fields
    
    # We maintain the class attribute names if they were accessed as User.KYCStatus
    KYCStatus = KYCStatus 

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    role = models.CharField(max_length=50, choices=Role.choices, default=Role.TRAVELER)
    kyc_status = models.CharField(max_length=20, choices=KYCStatus.choices, default=KYCStatus.UNVERIFIED)
    
    # Kiosk Identity
    kiosk_id = models.CharField(max_length=100, blank=True, null=True, help_text="Hardware ID if this user is a Kiosk")
    
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    verification_code = models.CharField(max_length=6, blank=True, null=True, help_text="6-digit OTP for email verification")

    # Tourist registration fields
    NATIONALITY_CHOICES = (
        ('INDIAN', 'Indian National'),
        ('FOREIGN', 'Foreign National'),
    )
    nationality = models.CharField(max_length=20, choices=NATIONALITY_CHOICES, default='INDIAN')
    country = models.CharField(max_length=100, blank=True, null=True)
    identity_type = models.CharField(max_length=50, blank=True, null=True)
    identity_value = models.CharField(max_length=120, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    
    email = models.EmailField(unique=True)

    # We will link District later to avoid circular imports during initial migration or use string
    # district = models.ForeignKey('geography.District', ...)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username'] # Email and password are required by default with USERNAME_FIELD

    def __str__(self):
        return f"{self.username} ({self.role})"

class InviteCode(models.Model):
    code = models.CharField(max_length=50, unique=True)
    assigned_role = models.CharField(max_length=50, choices=User.Role.choices)
    # district = models.ForeignKey(...) # TODO: Link to Geography
    
    max_usage = models.IntegerField(default=1)
    current_usage = models.IntegerField(default=0)
    expiry_date = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_invites')
    created_at = models.DateTimeField(auto_now_add=True)

    def is_valid(self):
        from django.utils import timezone
        if not self.is_active: return False
        if self.current_usage >= self.max_usage: return False
        if self.expiry_date and timezone.now() > self.expiry_date: return False
        return True

class ConnectCode(models.Model):
    """
    Short-lived 6-digit code for Kiosk-Mobile handshake.
    Generated by Mobile (Authenticated User), Consumed by Kiosk (Public).
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False)

    def is_valid(self):
        from django.utils import timezone
        return not self.is_used and self.expires_at > timezone.now()

    def __str__(self):
        return f"{self.code} - {self.user.email}"


    def __str__(self):
        return self.code
