# Generated by Django 5.2.10 on 2026-01-18 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrowTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_reference",
                    models.CharField(
                        help_text="ID of the item/service", max_length=255
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "buyer_handshake_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Seller scans this to prove Buyer presence",
                    ),
                ),
                (
                    "product_handshake_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Buyer scans this to prove Item receipt",
                    ),
                ),
                ("buyer_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("seller_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved (Funds Held)"),
                            ("LOCKED", "Locked (Awaiting Meetup)"),
                            ("VERIFIED", "Handshake Verified"),
                            ("RELEASED", "Funds Released"),
                            ("DISPUTED", "Dispute Raised"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RESERVED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
