# Generated by Django 6.0 on 2026-01-20 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_escrowtransaction_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("VENDOR_CONFIRMED", "Vendor Confirmed"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("kiosk_id", models.CharField(blank=True, max_length=50, null=True)),
                ("district_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "amount_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vendor_id", models.IntegerField(help_text="Reference ID for pilot")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="host",
        ),
        migrations.CreateModel(
            name="DealToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("TRAVELER_INTENT", "Traveler Intent"),
                            ("VENDOR_CONFIRM", "Vendor Confirm"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_value", models.UUIDField(default=uuid.uuid4)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="commerce.deal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deal",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="commerce.product"
            ),
        ),
        migrations.DeleteModel(
            name="EscrowTransaction",
        ),
        migrations.DeleteModel(
            name="QRCode",
        ),
    ]
