# Generated by Django 5.2.10 on 2026-01-19 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_hotspot_duration_minutes_hotspot_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hotspot",
            name="accessibility_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_hotspots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="operating_hours",
            field=models.CharField(
                blank=True, help_text="e.g., '09:00 - 17:00'", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="safety_notes",
            field=models.TextField(blank=True, help_text="Public safety warnings"),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="seasons",
            field=models.JSONField(
                blank=True, default=list, help_text="e.g., ['Winter', 'Spring']"
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="sensitivity_level",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("PROTECTED", "Protected (Generalized)"),
                    ("RESTRICTED", "Restricted (Hidden)"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hotspot",
            name="short_description",
            field=models.CharField(
                default="Summary", help_text="Tweet-sized summary", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotspot",
            name="village_cluster_label",
            field=models.CharField(
                default="Cluster",
                help_text="Public safe label (e.g., 'Upper Majuli Cluster')",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="media",
            name="compliance_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="media",
            name="compliance_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="media",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hotspot",
            name="description",
            field=models.TextField(help_text="Full detailed narrative"),
        ),
        migrations.AlterField(
            model_name="hotspot",
            name="duration_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hotspot",
            name="moderation_notes",
            field=models.TextField(blank=True, help_text="Internal notes"),
        ),
        migrations.AlterField(
            model_name="hotspot",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("CHANGES_REQUESTED", "Changes Requested"),
                    ("APPROVED", "Approved"),
                    ("LIVE", "Live"),
                    ("SUSPENDED", "Suspended"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hotspot",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="ModerationTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("SENSITIVE_INFO", "Sensitive Info Risk"),
                            ("PII_RISK", "PII Risk"),
                            ("POLICY_VIOLATION", "Policy Violation"),
                            ("QUALITY_FIX", "Quality Fix"),
                            ("DISALLOWED_PHRASE", "Disallowed Phrase"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_moderation_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotspot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="listings.hotspot",
                    ),
                ),
            ],
        ),
    ]
