# Generated by Django 6.0 on 2026-01-06 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KioskDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name: e.g. 'North Gate Kiosk 1'",
                        max_length=100,
                    ),
                ),
                (
                    "hardware_id",
                    models.CharField(
                        help_text="Hardware Serial / MAC", max_length=100, unique=True
                    ),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MAINTENANCE", "Maintenance"),
                            ("DECOMMISSIONED", "Decommissioned"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "api_key_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hashed API Key for auth",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KioskHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ipv4", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status_payload",
                    models.JSONField(default=dict, help_text="Device health metrics"),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to="kiosk.kioskdevice",
                    ),
                ),
            ],
        ),
    ]
