# Generated by Django 6.0 on 2026-01-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="6-digit OTP for email verification",
                max_length=6,
                null=True,
            ),
        ),
    ]
